### ISSUE TITLE
🚆🚆🚆 Hop-in

### ISSUE THREAD

**Issue by matyasjay** [HiImZsofi/mav-bot#24]
Hey guys, this project looks brilliant! I'm working as a sw engineer for a couple of years and quite interested participating in such an iconic product during my spare time. Would you recommend me some tasks I could work on as an entry? However I'm currently a lead fronend dev working with React and stuff, I'm also fluent in node end express and up to dive into anything.

**Comment by HiImZsofi** [comment]
Hello, thank you so much for the kind words! :) We are actually thought about developing a website for the app where people could access the tables in a .csv format. If you are interested in joining us, please contact me on Discord: Zsófi#0853, or on Twitter: https://twitter.com/HeyImSophie00. I am looking forwards hearing from you!
